contao:
    localconfig:
        licenseAccepted: true
        enableSearch: false
        disableCron: true
        folderUrl: false

        dateFormat: "d.m.Y"
        datimFormat: "d.m.Y H:i"
        timeZone: 'Europe/Berlin'
    
    image:
        valid_extensions: [ jpg, jpeg, gif, png, tif, tiff, bmp, svg, svgz, webp ]